project:
  type: website
  output-dir: docs

website:
  title: "Chengwei Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
<<<<<<< HEAD
      - href: hw1.qmd
        text: HW1
=======
>>>>>>> df52f0c67ba0b50b301b34bf17b533dc26edd261

format:
  html:
    theme: cosmo
    toc: true